### ISSUE TITLE
Error in s3_operations.pl file

### ISSUE THREAD

**Issue by anandmadhab** [sudo-batman/perl-toolkit#1]
Global symbol "$config" requires explicit package name at s3_operations.pl:33

**Comment by anandmadhab** [comment]
did any one face this issue?

**Comment by rai-gaurav** [comment]
Thanks fort the report. I have created the .pl script mostly as an example and hence maybe forgot to declare it. The.pm files are the actual one. I have fixed this issue for couple of scripts and it should work now(https://github.com/sudo-batman/perl-toolkit/commit/f7c3128352d7ec254dd7de869c9524fb52b5279b). Thanks for the report.
