### ISSUE TITLE
AWS CLI not working

### ISSUE THREAD

**Issue by anandmadhab** [sudo-batman/perl-toolkit#2]
Executing 'aws s3 cp s3://bucketName/keyName/dirname/filename'
Can't exec "aws": No such file or directory

I just want to see if we can call AWS CLI directly from perl without using Paws?

**Comment by rai-gaurav** [comment]
There is no need for Paws. You need to install awscli first from - https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2.html. There are different OS option available.
The very first requirement for this script is aws command line interface as you will need a client to perform the operations.
Please go through the [Readme](https://github.com/sudo-batman/perl-toolkit/blob/master/AWS/README.md)

**Comment by anandmadhab** [comment]
after installing awscli it worked, Thanks.
